import type { APIRoute } from "astro";

const getRobotsTxt = (siteURL: URL) => `\
User-agent: *
Allow: /

# Main sitemap (auto-generated by @astrojs/sitemap)
Sitemap: ${new URL("sitemap-index.xml", siteURL).href}

# Master sitemap index (includes all external VitePress documentation sites)
Sitemap: ${new URL("sitemap-master.xml", siteURL).href}
`;

export const GET: APIRoute = ({ site }) => {
  return new Response(getRobotsTxt(site!));
};
