name: Publish README to GitHub Pages Docs

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  publish-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up repository name
        id: repo-name
        run: echo "name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Clone central docs repository
        run: |
          git clone https://github.com/muhammad-fiaz/muhammad-fiaz.github.io.git central-docs
          cd central-docs
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Copy README to docs/repo-name
        run: |
          mkdir -p central-docs/docs/$name
          cp README.md central-docs/docs/$name/README.md

      - name: Commit and push changes
        run: |
          cd central-docs
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update docs for $name"
            git push
          fi
